camunda:
  bpm:
    auto-deployment-enabled: true
    authorization:
      enabled: true

backbase:
  activemq:
    enabled: false
  flow:
    iam.local.users:
      - id: user
        fullName: John Doe
        permissions:
          - case(view) on case-definition:case-definition
          - case(create) on case-definition:case-definition
          - task(view) on process-definition:simple-process
          - task(execute) on process-definition:simple-process
    case-definitions:
      definitions:
        case-definition:
          case-classes:
            - name: com.example.flow.casedata.CaseDefinition
              version: 1
          case-status-definitions:
            - name: Primary case status
              isPrimary: true
              values:
                - open
                - in progress
                - closed
              provider: com.example.flow.status.PrimaryCaseStatusProvider
    storage:
      impl: fs
      fs:
        baseDir: ${java.io.tmpdir}/simple-document-storage

sso:
  jwt:
    internal:
      signature:
        key:
          type: VALUE
          value: "JWTSecretKeyDontUseInProduction!"

eureka:
  instance:
    appname: ${spring.application.name}
    healthCheckUrlPath: /production-support/health
    statusPageUrlPath: /production-support/info
    nonSecurePort: ${server.port}
    metadata-map:
      public: true
      role: live
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/registry/eureka/

buildingblocks:
  security:
    csrf:
      enabled: false

spring:
  main:
    allow-bean-definition-overriding: true