spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/send-personal-message-flow
    username: root
    password: root
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    database:
      type: mysql
server:
  port: 9091
migration:
  sourceDefinition:
      key: "send-personal-message"
      version: "1.0.0"
  targetDefinition:
      key: "send-personal-message"
      version: "1.1.0"
  updateEventTriggers: false
  skipIoMappings: false
  skipCustomListeners: false